### ISSUE TITLE
Correct answer is not working 

### ISSUE THREAD

**Issue by mateotop** [alvaro-cas/studier-obsidian#2]
Hey there, I've been trying to create a quiz, but unfortunately, the `- !` symbol isn't working. Here's my test Markdown code and a few pictures.

```markdown 
> [!info]- Questions
 >1. Which letter is the third letter in the English alphabet?
> - a 
> - b 
> - c - !
>---
```

And that's what I'm seeing in the Studier's window.
![image](https://github.com/alvaro-cas/studier-obsidian/assets/105502841/10f8627e-bdde-4198-bdda-ec211041e7f2)

Any ideas on what I might be doing wrong?

**Comment by mateotop** [comment]
I've also tried adjusting the spacing between the `!` and the `-`, but it hasn't made a difference.

[ My markdown ]
```markdown 
> [!info]- Questions
>1. Which letter is the third letter in the English alphabet?
> - a 
> - b 
> - c - !
> - c -!
> - c-!
> - c- !
>---
``` 

[ Quizzing ]  
I see a `- !`, but I think it shouldn't be that way.
![image](https://github.com/alvaro-cas/studier-obsidian/assets/105502841/f5524741-f542-4353-b66e-571583dbd99c)

[ Checking the answer ]  
I've been getting some weird stuff after pressing the `Check` button. It seems like there's some kind of return from `JavaScript` or `TypeScript` that's coming back as `undefined` instead of the actual answer.
![image](https://github.com/alvaro-cas/studier-obsidian/assets/105502841/3983b8d5-33f4-4a93-a144-ce2826c8d68f)

![image](https://github.com/alvaro-cas/studier-obsidian/assets/105502841/0386342b-74a6-4def-9aef-70df43fa5cc2)

**Comment by alvaro-cas** [comment]
Hi there! Thank you for telling me about the issue you're experiencing. It seems like the problem is with how things are set up. Did you have a chance to read the [README](https://github.com/alvaro-cas/studier-obsidian/blob/main/README.md)? It has some helpful information on how to customize things to your liking. If the instructions are confusing, please let me know, and I'll make them clearer. To fix the problem, you'll need to change the settings like this:

![sample_settings](https://github.com/alvaro-cas/studier-obsidian/assets/121831581/a8171490-df44-4f38-ad83-3b4c9e78a243)

Remember that in this [situation](https://github.com/alvaro-cas/studier-obsidian/issues/2#issuecomment-2017538799), there are two right answers. So if you pick the first one, it will be considered incorrect.
